### ISSUE TITLE
502: BAD_GATEWAY

### ISSUE THREAD

**Issue by caffeine-lab** [natemoo-re/natemoo-re#11]
Hello !

After multiple attempts, I am still stuck with the same error. I don't understand where I am going wrong here.
Any help would be appreciated.

![image](https://user-images.githubusercontent.com/61284219/89587794-f610a480-d85f-11ea-896b-165a366ffb79.png)

**Comment by izyhang** [comment]
> Hello !
> 
> After multiple attempts, I am still stuck with the same error. I don't understand where I am going wrong here.
> Any help would be appreciated.
> 
> ![image](https://user-images.githubusercontent.com/61284219/89587794-f610a480-d85f-11ea-896b-165a366ffb79.png)

i got the same problem.
after make sure all Environment Variables is right and redeploy, it finally success

**Comment by caffeine-lab** [comment]
> > Hello !
> > After multiple attempts, I am still stuck with the same error. I don't understand where I am going wrong here.
> > Any help would be appreciated.
> > ![image](https://user-images.githubusercontent.com/61284219/89587794-f610a480-d85f-11ea-896b-165a366ffb79.png)
> 
> i got the same problem.
> after make sure all Environment Variables is right and redeploy, it finally success

When I tried to redeploy I am continuously getting this error "Unable to redeploy, please try again shortly.", I have no idea why it is.

**Comment by izyhang** [comment]
@caffeine-lab you can just push anything to your git to trigger Git Integrations, or what i did is Delete Deployment and Deploy again

**Comment by caffeine-lab** [comment]
@izyhang 
Yup worked now Thanks!

**Comment by Anthony-hcy** [comment]
> @izyhang Yup worked now Thanks! Yup现在工作了谢谢！

Hello, I have also encountered this problem and am very distressed. Have you solved this problem yet?
![image](https://github.com/user-attachments/assets/9c4551d2-ff80-40f9-bfd2-c43950de9309)
