### ISSUE TITLE
How to render image on Readme

### ISSUE THREAD

**Issue by npitsillos** [natemoo-re/natemoo-re#12]
Hello, this might be a bit irrelevant but this is the place I could ask.  I wanted to do something similar but for discord in order to capture what kind of game a user is playing.  I got the most part after using your code however when I get the following image url: 

https://cdn.discordapp.com/app-assets/401518684763586560/416719019576393738.webp

(after navigating the Discord.js objects) I set this to be the `src `value of the `<img>` tag like so:

`<img id="cover" src={imageUrl} width="48" height="48" />`.

![image](https://user-images.githubusercontent.com/9141826/90965501-91408580-e4c0-11ea-9640-916f972ce746.png)

You can see the result in Vercel however the image does not appear in my github readme.

Any chance you could help out?

Thank you this was a nice idea!

**Comment by npitsillos** [comment]
Yes it does thank you! But one small thing, what `now-playing` returns is an HTML representation of the Player right? In my case I use FastAPI because I am not good with typescript or javascript which means I need to write the HTML code myself but then sending the response as image/svg+xml does not work. For example take a look at the code below:
```
if image_url is not None:
    res = requests.get(image_url)
    base_64_str = "data:image/png;base64,"  + base64.b64encode(res.content).decode("utf-8") 
    data = "<svg fill='none' width='256' height='64' viewBox='0 0 256 64' xmlns='http://www.w3.org/2000/svg'><foreignObject widht='256' height='64'><img src='{0}' style='{1}' alt='{2}' width='48' height='48'></img>{3}</foreignObject></svg>".format(base_64_str, GAME_STYLE, game_name.replace(' ', ''), game_name)
else:
    data = "<svg fill='none' width='256' height='64' viewBox='0 0 256 64' xmlns='http://www.w3.org/2000/svg'><foreignObject widht='256' height='64'><img src='{0}' style='{1}' width='48' height='48'></img>Nothing Playing</foreignObject></svg>".format(NO_GAME_IMAGE, NO_GAME_STYLE)
    print(game_name)
    return Response(content=data,  media_type="image/svg+xml")
```

This does not render when I add the following `<img src=http://localhost:8000/> when testing.  If you have any tips that would be amazing! Thank you.

**Comment by natemoo-re** [comment]
Yep, it just returns a valid SVG document! Using TypeScript and React is definitely overcomplicating things, but I just hacked something together using the tools I'm most familiar with.

I think you need to wrap everything inside the `foreignObject` with a single parent `div`. Since you're embedding HTML inside of an SVG, that root `div` needs to include the correct namespace – add `xmlns="http://www.w3.org/1999/xhtml"` per the MDN [`foreignObject`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) docs. Also your `foreignObject` has a typo – `widht` should be `width`.

**Comment by npitsillos** [comment]
Thank you I did that and even though I tried it before I must have typed the div wrong as well. Thank you this works!
