### ISSUE TITLE
Top tracks not working

### ISSUE THREAD

**Issue by wesbz** [natemoo-re/natemoo-re#14]
Hi,
very cool work! I've been trying to use it but could not figure out how to have the "top-tracks" feature to work. I see 
![this](https://user-images.githubusercontent.com/5843554/102220897-ba5aab00-3ee1-11eb-9a17-8f517a128f6b.png)
after following your instructions. Do you know what might be happening?
Thanks in advance :)

**Comment by natemoo-re** [comment]
Hmm, I suspect something about the `scope` is not configured correctly. Any token is tied to the scopes it requested when it was created, so if you generated one previously it may not include [`user-top-read`](https://developer.spotify.com/documentation/general/guides/scopes/#user-top-read).

Can you try to generate a new token and ensure that the Spotify permission request includes "Read your top artists and content."?

**Comment by wesbz** [comment]
Thanks for your reply! Requesting another refresh token was indeed the solution! Thanks!
