### ISSUE TITLE
Always nothing playing

### ISSUE THREAD

**Issue by SamFreaks** [natemoo-re/natemoo-re#19]
Hey, i deploy your repo on Vercel, but it always says nothinh playing.....

**Comment by SamFreaks** [comment]
Now it works

**Comment by Anthony-hcy** [comment]
Hello, I have  encountered this problem and am very distressed. Have you solved this problem yet?
![image](https://github.com/user-attachments/assets/721a2ee1-428e-407b-b1b8-9a3a3c4a35af)
