### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by livrasand** [natemoo-re/natemoo-re#29]
![imagen](https://github.com/natemoo-re/natemoo-re/assets/104039397/fd1125a5-6b00-4252-a0bf-5a27a19a92e2)

Hello, I have followed all these steps:

https://github.com/livrasand/now-playing-profile/blob/master/spotify-setup-guide.md

But it keeps giving me that error

What am I doing wrong?

**Comment by Anthony-hcy** [comment]
Hello, I have also encountered this problem and am very distressed. Have you solved this problem yet?
![image](https://github.com/user-attachments/assets/240568ca-b419-4ae9-9885-39cf40920138)
